/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ukh_modules_distribution_system;

import java.io.*;
import java.util.*;
import javax.swing.JOptionPane;



/**
 *
 * @author Balen
 */
public class addSubjectForm extends javax.swing.JFrame {

    static String fileDir = "./Subject.txt";  //file directory
    static String courseDir = "./Course.txt";  //file directory
    
    
    /**
     * Creates new form addStudentFrame
     */
    public addSubjectForm() {
        initComponents();
        getComboList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        subNameLbl = new javax.swing.JLabel();
        subIdLbl = new javax.swing.JLabel();
        subCreditLbl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        addSubjectBtn = new javax.swing.JButton();
        subNameTxt = new javax.swing.JTextField();
        subIDTxt = new javax.swing.JTextField();
        subCreditTxt = new javax.swing.JTextField();
        subjectCombo = new javax.swing.JComboBox<>();
        DepLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        subNameLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        subNameLbl.setForeground(new java.awt.Color(255, 255, 255));
        subNameLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subNameLbl.setText("Subject name:");

        subIdLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        subIdLbl.setForeground(new java.awt.Color(255, 255, 255));
        subIdLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subIdLbl.setText("Subject ID:");

        subCreditLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        subCreditLbl.setForeground(new java.awt.Color(255, 255, 255));
        subCreditLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subCreditLbl.setText("Number of Credits:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Add Subject form");

        addSubjectBtn.setBackground(new java.awt.Color(0, 0, 0));
        addSubjectBtn.setForeground(new java.awt.Color(255, 255, 255));
        addSubjectBtn.setText("Add");
        addSubjectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSubjectBtnActionPerformed(evt);
            }
        });

        subNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subNameTxtActionPerformed(evt);
            }
        });

        subjectCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectComboActionPerformed(evt);
            }
        });

        DepLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DepLbl.setForeground(new java.awt.Color(255, 255, 255));
        DepLbl.setText("Program:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addSubjectBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(142, 142, 142))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(subCreditLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DepLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(subIdLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(subNameLbl, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(subNameTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                        .addComponent(subIDTxt, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(subCreditTxt, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(subjectCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subNameLbl)
                    .addComponent(subNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subIdLbl)
                    .addComponent(subIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subCreditTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subCreditLbl))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subjectCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DepLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(addSubjectBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addSubjectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSubjectBtnActionPerformed
        
        
        String subjectName = subNameTxt.getText();
        String subjectID = subIDTxt.getText();
        int subjectCredit = 0;
        String comboText = subjectCombo.getSelectedItem().toString();
        String [] splitted = comboText.split("\\s*,\\s*");
        String CourseID = splitted[1];
        
        
        boolean auth = true;  // if any error happens auth will be false otherwise its true
        
        
        try{
        subjectCredit = Integer.parseInt(subCreditTxt.getText());
        }
        catch (NumberFormatException e){          // We have studied number format exception in class
            JOptionPane.showMessageDialog(null, "Invalid credit number!!");
            auth = false;
        }
        
        
        //check for empty fields
        if(subjectName.isEmpty()){
            JOptionPane.showMessageDialog(null, "Subject name is empty");
            auth = false;
        }
        if(subjectID.isEmpty()){
            JOptionPane.showMessageDialog(null, "Subject ID is empty");
            auth = false;
        }
        if(CourseID.isEmpty()){
            JOptionPane.showMessageDialog(null, "Course ID is not selected");
            auth = false;
        }
        
        
        Subject newSubject = new Subject(subjectName, subjectCredit, subjectID, CourseID);
        
        ArrayList <Subject> AllSubjects = new ArrayList <Subject>();
        
        
        // To read all available data first
        if(auth){
        try {
        
            ObjectInputStream read = new ObjectInputStream(new FileInputStream(fileDir));
            Object o; // an object of Object class (The parent of all objects)
            
            try{
                o = read.readObject();
                if(o != null)
                AllSubjects = (ArrayList<Subject>) o;
            }
            catch(IOException | ClassNotFoundException c){
                c.printStackTrace();
                
            }
            
            read.close();
        }
        
        catch(IOException outer){
            outer.printStackTrace();
            
        }
        
        
        
        
        // to write the data
        
        try {
            FileOutputStream fileOutput = new FileOutputStream(fileDir);
            ObjectOutputStream write = new ObjectOutputStream(fileOutput); 
		
            ArrayList <Subject> addSubject = new ArrayList <Subject>();
            addSubject = AllSubjects;
            addSubject.add(newSubject);
            write.writeObject(addSubject);
            write.close();
            JOptionPane.showMessageDialog(null, "Subject Successfully added");
       	      
            write.close();
        } catch (IOException e) {
            
            JOptionPane.showMessageDialog(null, "error");
	}
        
        }
        
        
        clearFields();
    }//GEN-LAST:event_addSubjectBtnActionPerformed

    private void subNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subNameTxtActionPerformed

    private void subjectComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectComboActionPerformed
       
    }//GEN-LAST:event_subjectComboActionPerformed

    private void getComboList(){
        ArrayList <Course> AllCourses = new ArrayList <Course>();
        
        try{
            ObjectInputStream read = new ObjectInputStream(new FileInputStream(courseDir));

            Object o;
            
           
            try{
                o = read.readObject();
                if(o != null)
                AllCourses = (ArrayList<Course>) o;
            }
            catch(IOException | ClassNotFoundException c){
                c.printStackTrace();
                System.out.println("Here");
            }
            
				
	read.close();
        
        for(int i = 0; i < AllCourses.size(); i++){
            String option = AllCourses.get(i).getCourseName()  + ", " + AllCourses.get(i).getCourseId();
            subjectCombo.addItem(option);
        }
	
        
        }
        catch(IOException e){
            e.printStackTrace();
        }
        
        
        
    }
    
    //reset all text fields
    private void clearFields(){
    
        subNameTxt.setText("");
        subIDTxt.setText("");
        subCreditTxt.setText("");
        subjectCombo.setSelectedIndex(0);
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addSubjectForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addSubjectForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addSubjectForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addSubjectForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addSubjectForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DepLbl;
    private javax.swing.JButton addSubjectBtn;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel subCreditLbl;
    private javax.swing.JTextField subCreditTxt;
    private javax.swing.JTextField subIDTxt;
    private javax.swing.JLabel subIdLbl;
    private javax.swing.JLabel subNameLbl;
    private javax.swing.JTextField subNameTxt;
    private javax.swing.JComboBox<String> subjectCombo;
    // End of variables declaration//GEN-END:variables
}
