/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ukh_modules_distribution_system;

/**
 *
 * @author Balen
 */
public class adminPage extends javax.swing.JFrame {

    /**
     * Creates new form adminPage
     */
    public adminPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adminPanel = new javax.swing.JPanel();
        signoutBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        showStudentBtn = new javax.swing.JButton();
        addStudentBtn = new javax.swing.JButton();
        showInstructorBtn = new javax.swing.JButton();
        addInstructorBtn = new javax.swing.JButton();
        showLecturerBtn = new javax.swing.JButton();
        addLecturerBtn = new javax.swing.JButton();
        addProgramBtn = new javax.swing.JButton();
        showSubjectBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        showProgramBtn = new javax.swing.JButton();
        addSubjectBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        adminPanel.setBackground(new java.awt.Color(51, 51, 51));

        signoutBtn.setBackground(new java.awt.Color(0, 0, 0));
        signoutBtn.setForeground(new java.awt.Color(255, 255, 255));
        signoutBtn.setText("Sign out");
        signoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signoutBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Subjects");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Programs");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Lecturers");

        showStudentBtn.setBackground(new java.awt.Color(0, 0, 0));
        showStudentBtn.setForeground(new java.awt.Color(255, 255, 255));
        showStudentBtn.setText("Show List");
        showStudentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showStudentBtnActionPerformed(evt);
            }
        });

        addStudentBtn.setBackground(new java.awt.Color(0, 0, 0));
        addStudentBtn.setForeground(new java.awt.Color(255, 255, 255));
        addStudentBtn.setText("Add");
        addStudentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentBtnActionPerformed(evt);
            }
        });

        showInstructorBtn.setBackground(new java.awt.Color(0, 0, 0));
        showInstructorBtn.setForeground(new java.awt.Color(255, 255, 255));
        showInstructorBtn.setText("Show List");
        showInstructorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showInstructorBtnActionPerformed(evt);
            }
        });

        addInstructorBtn.setBackground(new java.awt.Color(0, 0, 0));
        addInstructorBtn.setForeground(new java.awt.Color(255, 255, 255));
        addInstructorBtn.setText("Add");
        addInstructorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addInstructorBtnActionPerformed(evt);
            }
        });

        showLecturerBtn.setBackground(new java.awt.Color(0, 0, 0));
        showLecturerBtn.setForeground(new java.awt.Color(255, 255, 255));
        showLecturerBtn.setText("Show List");
        showLecturerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showLecturerBtnActionPerformed(evt);
            }
        });

        addLecturerBtn.setBackground(new java.awt.Color(0, 0, 0));
        addLecturerBtn.setForeground(new java.awt.Color(255, 255, 255));
        addLecturerBtn.setText("Add");
        addLecturerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLecturerBtnActionPerformed(evt);
            }
        });

        addProgramBtn.setBackground(new java.awt.Color(0, 0, 0));
        addProgramBtn.setForeground(new java.awt.Color(255, 255, 255));
        addProgramBtn.setText("Add");
        addProgramBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProgramBtnActionPerformed(evt);
            }
        });

        showSubjectBtn.setBackground(new java.awt.Color(0, 0, 0));
        showSubjectBtn.setForeground(new java.awt.Color(255, 255, 255));
        showSubjectBtn.setText("Show List");
        showSubjectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showSubjectBtnActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Students");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Instructors");

        showProgramBtn.setBackground(new java.awt.Color(0, 0, 0));
        showProgramBtn.setForeground(new java.awt.Color(255, 255, 255));
        showProgramBtn.setText("Show List");
        showProgramBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showProgramBtnActionPerformed(evt);
            }
        });

        addSubjectBtn.setBackground(new java.awt.Color(0, 0, 0));
        addSubjectBtn.setForeground(new java.awt.Color(255, 255, 255));
        addSubjectBtn.setText("Add");
        addSubjectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSubjectBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout adminPanelLayout = new javax.swing.GroupLayout(adminPanel);
        adminPanel.setLayout(adminPanelLayout);
        adminPanelLayout.setHorizontalGroup(
            adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(signoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
            .addGroup(adminPanelLayout.createSequentialGroup()
                .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(adminPanelLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(showSubjectBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addSubjectBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(140, 140, 140)
                        .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addProgramBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(showProgramBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(adminPanelLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(showStudentBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addStudentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(131, 131, 131)
                        .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(showInstructorBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                            .addComponent(addInstructorBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                        .addGap(130, 130, 130)
                        .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(showLecturerBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                            .addComponent(addLecturerBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        adminPanelLayout.setVerticalGroup(
            adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminPanelLayout.createSequentialGroup()
                        .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(adminPanelLayout.createSequentialGroup()
                                .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(showInstructorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(showLecturerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(addInstructorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addLecturerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(adminPanelLayout.createSequentialGroup()
                                .addComponent(showStudentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(addStudentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(74, 74, 74)
                        .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(showProgramBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(showSubjectBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addProgramBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addSubjectBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(836, 836, 836))
                    .addGroup(adminPanelLayout.createSequentialGroup()
                        .addComponent(signoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adminPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adminPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 447, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signoutBtnActionPerformed
        this.dispose();
        LoginPage login = new LoginPage();
        login.setVisible(true);
        
        
    }//GEN-LAST:event_signoutBtnActionPerformed

    private void showStudentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showStudentBtnActionPerformed
        showStudentFrame showstudent = new showStudentFrame();
        showstudent.setVisible(true);
        showstudent.setDefaultCloseOperation(showstudent.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_showStudentBtnActionPerformed

    private void showInstructorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showInstructorBtnActionPerformed
        showInstructorFrame showInstructor = new showInstructorFrame();
        showInstructor.setVisible(true);
        showInstructor.setDefaultCloseOperation(showInstructor.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_showInstructorBtnActionPerformed

    private void showLecturerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showLecturerBtnActionPerformed
        
        showLecturerFrame showshowLecturer = new showLecturerFrame();
        showshowLecturer.setVisible(true);
        showshowLecturer.setDefaultCloseOperation(showshowLecturer.DISPOSE_ON_CLOSE);
        
    }//GEN-LAST:event_showLecturerBtnActionPerformed

    private void showSubjectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showSubjectBtnActionPerformed
        
        showSubjectFrame showSubject = new showSubjectFrame();
        showSubject.setVisible(true);
        showSubject.setDefaultCloseOperation(showSubject.DISPOSE_ON_CLOSE);
        
        
    }//GEN-LAST:event_showSubjectBtnActionPerformed

    private void showProgramBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showProgramBtnActionPerformed
        
        showProgramFrame showProgram = new showProgramFrame();
        showProgram.setVisible(true);
        showProgram.setDefaultCloseOperation(showProgram.DISPOSE_ON_CLOSE);
        
    }//GEN-LAST:event_showProgramBtnActionPerformed

    private void addProgramBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProgramBtnActionPerformed
        addCourse courseForm = new addCourse();
        courseForm.setVisible(true);
        courseForm.setDefaultCloseOperation(courseForm.DISPOSE_ON_CLOSE);
        // to make the main frame (admin panel stay opened) by default its exit on close
        // for dispose_on_close I learned from 
        //https://stackoverflow.com/questions/20663842/why-does-closing-sub-frame-close-also-the-main-frame-in-java-swing
        
    }//GEN-LAST:event_addProgramBtnActionPerformed

    private void addSubjectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSubjectBtnActionPerformed
    
        addSubjectForm subjectForm = new addSubjectForm();
        subjectForm.setVisible(true);
        subjectForm.setDefaultCloseOperation(subjectForm.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_addSubjectBtnActionPerformed

    private void addStudentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentBtnActionPerformed
        addStudentFrame studentFrame = new addStudentFrame();
        studentFrame.setVisible(true);
        studentFrame.setDefaultCloseOperation(studentFrame.DISPOSE_ON_CLOSE); 
        
    }//GEN-LAST:event_addStudentBtnActionPerformed

    private void addLecturerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLecturerBtnActionPerformed
        
        addLecturerForm lecturerForm = new addLecturerForm();
        lecturerForm.setVisible(true);
        lecturerForm.setDefaultCloseOperation(lecturerForm.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_addLecturerBtnActionPerformed

    private void addInstructorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addInstructorBtnActionPerformed
        
        addInstructorForm instructorForm = new addInstructorForm();
        instructorForm.setVisible(true);
        instructorForm.setDefaultCloseOperation(instructorForm.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_addInstructorBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addInstructorBtn;
    private javax.swing.JButton addLecturerBtn;
    private javax.swing.JButton addProgramBtn;
    private javax.swing.JButton addStudentBtn;
    private javax.swing.JButton addSubjectBtn;
    private javax.swing.JPanel adminPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton showInstructorBtn;
    private javax.swing.JButton showLecturerBtn;
    private javax.swing.JButton showProgramBtn;
    private javax.swing.JButton showStudentBtn;
    private javax.swing.JButton showSubjectBtn;
    private javax.swing.JButton signoutBtn;
    // End of variables declaration//GEN-END:variables
}
