/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ukh_modules_distribution_system;

import java.io.*;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;





/**
 *
 * @author Balen
 */
public class showStudentFrame extends javax.swing.JFrame {
    
    static String studentDir = "./student.txt";  //file directory
    
    ArrayList <Student> AllStudents = new ArrayList <Student>(); // to put all students data into it
    String tableHeaders [] = new String[] {"ID number", "Name" , "Email", "phone", "Address", "CourseID"};
    DefaultTableModel studentModel;
    int foundIndex;
    
    
    int row;  // to get the row number
    
    // got inspiration from https://www.tutorialspoint.com/how-to-create-defaulttablemodel-which-is-an-implementation-of-tablemodel
    // not copied
    
    
    
    /**
     * Creates new form showStudentFrame
     */
    public showStudentFrame() {
        initComponents();
        
        
        
        // we should set the table model directly when the frame appears
        studentModel = new DefaultTableModel(tableHeaders, 0);
        studentTbl.setModel(studentModel);
        
        
        this.setLocationRelativeTo(null); // Make the frame centered to the screen when we opened
        //https://coderanch.com/t/343686/java/setLocationRelativeTo
        getData();
        listStudents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentTbl = new javax.swing.JTable();
        saveBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        searchTxt = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        studentTbl = new javax.swing.JTable(){

            public boolean isCellEditable(int row, int column) {
                return false;
            }

        };
        studentTbl.setForeground(new java.awt.Color(0, 0, 0));
        studentTbl.setFocusable(false);
        studentTbl.getTableHeader().setReorderingAllowed(false);
        studentTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentTblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(studentTbl);

        saveBtn.setBackground(new java.awt.Color(51, 0, 255));
        saveBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        saveBtn.setForeground(new java.awt.Color(255, 255, 255));
        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        deleteBtn.setBackground(new java.awt.Color(153, 0, 0));
        deleteBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        searchBtn.setBackground(new java.awt.Color(0, 0, 0));
        searchBtn.setForeground(new java.awt.Color(255, 255, 255));
        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Student ID:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 713, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studentTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentTblMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_studentTblMouseClicked

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        
        
        DefaultTableModel tableModel = (DefaultTableModel) studentTbl.getModel();
        
        if(foundIndex == -1){
        //to delete the row
        if (studentTbl.getSelectedRowCount() == 1){
        
            // if only a single row selected perform delete
            
            int r = studentTbl.getSelectedRow();
            
            tableModel.removeRow(r);
            AllStudents.remove(r);
        
        }
        
        else if (studentTbl.getSelectedRowCount() == 0) {
        
            // if the table empty (no data) then dislay a message
           
            JOptionPane.showMessageDialog(null, "Nothing is selected for delete");
        }
        
        else {
        // if row is not selected or multiple row selected
            JOptionPane.showMessageDialog(null, "Please select a single row for delete");
        }
        }
        
        
        
        
        //to delete data after search
        else {
            if (studentTbl.getSelectedRowCount() == 1){
        
            // if only a single row selected perform delete
            int selectedRow = studentTbl.getSelectedRow();
            
            tableModel.removeRow(selectedRow);
            AllStudents.remove(foundIndex);
        
        }
        
        else if (studentTbl.getSelectedRowCount() == 0) {
        
            // if the table empty (no data) then dislay a message
           
            JOptionPane.showMessageDialog(null, "The table is empty");
        }
        
        else {
        // if row is not selected or multiple row selected
            JOptionPane.showMessageDialog(null, "Please select a single row for delete");
        }
            
        }
        
        
        
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        //write into file permenantly
        
        try {
            FileOutputStream fileOutput = new FileOutputStream(studentDir);
            ObjectOutputStream write = new ObjectOutputStream(fileOutput); 
		
            ArrayList <Student> editedStudent = new ArrayList <Student>();
            editedStudent = AllStudents;
            
            write.writeObject(editedStudent);
            write.close();
            JOptionPane.showMessageDialog(null, "Saved successfuly");
       	      
            //write.close();
        } catch (IOException e) {
            
            JOptionPane.showMessageDialog(null, "error");
	}
        
        getData();
        listStudents();
    }//GEN-LAST:event_saveBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
       
        String searchID = searchTxt.getText();
        foundIndex = -1;
        
        
        if (!searchID.isEmpty()){
        for(int j = 0; j < AllStudents.size(); j++){
        
                if(AllStudents.get(j).getStudentID().equals(searchID)){
                    
                    JOptionPane.showMessageDialog(null, "Found!!");
                    foundIndex = j;
                
            }
        
        }
        
        if (foundIndex == -1){
            JOptionPane.showMessageDialog(null, "Not found");
        }
        
        if (foundIndex != -1)
        {
        studentModel.setRowCount(0); // reset the entire table
        Object[] info = {AllStudents.get(foundIndex).getStudentID(), AllStudents.get(foundIndex).getFirstName() + " " + AllStudents.get(foundIndex).getLastName() , AllStudents.get(foundIndex).getEmail(), AllStudents.get(foundIndex).getPhone(),  AllStudents.get(foundIndex).getAddress(), AllStudents.get(foundIndex).getCourseID() };
        studentModel.addRow(info);
        
        }
        }
        
        else{listStudents();}
           
    }//GEN-LAST:event_searchBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(showStudentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(showStudentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(showStudentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(showStudentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new showStudentFrame().setVisible(true);
            }
        });
    }
    
    private void getData(){
        
        try {
        
            ObjectInputStream read = new ObjectInputStream(new FileInputStream(studentDir));
            Object o; // an object of Object class (The parent of all objects)
            
            try{
                o = read.readObject();
                if(o != null)
                AllStudents = (ArrayList<Student>) o;
            }
            catch(IOException | ClassNotFoundException c){
                c.printStackTrace();
                
            }
            
            read.close();
        }
        
        catch(IOException outer){
            outer.printStackTrace();
            
        }
        
        
        
        
        
    
    }
    
    private void listStudents(){
    
        
        studentModel.setRowCount(0); // reset the entire table
        
        for(int i = 0 ; i < AllStudents.size(); i++){
            
            Object[] info = {AllStudents.get(i).getStudentID(), AllStudents.get(i).getFirstName() + " " + AllStudents.get(i).getLastName() , AllStudents.get(i).getEmail(), AllStudents.get(i).getPhone(),  AllStudents.get(i).getAddress(), AllStudents.get(i).getCourseID() };
        
            studentModel.addRow(info);
                
        }
        
        foundIndex = -1; // reset search result with update
        
    
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchTxt;
    private javax.swing.JTable studentTbl;
    // End of variables declaration//GEN-END:variables
}
